# 100 Numpy Exercises

###  1. Import the numpy package under the name

In [1]:
import numpy as np

### 2.  Print the numpy version and the configuration

In [2]:
print("NumPy Version:", np.__version__)
print("NumPy Configuration:")
print(np.show_config())

NumPy Version: 1.24.3
NumPy Configuration:
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/predictive_an001/miniconda3/envs/datascience/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/predictive_an001/miniconda3/envs/datascience/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/predictive_an001/miniconda3/envs/datascience/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/predictive_an001/miniconda3/envs/datascience/include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/predictive_an001/miniconda3/envs/datascience/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/predictive_an001/miniconda3/envs/datascience/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthre

### 3.  Create a null vector of size 10

In [3]:
null_vector = np.zeros(10)
print("Null vector of size 10:", null_vector)

Null vector of size 10: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 4.  How to find the memory size of any array

In [4]:
array = np.array([1, 2, 3, 4, 5])
print("Memory size of the array:", array.nbytes, "bytes")

Memory size of the array: 40 bytes


### 5. How to get the documentation of the numpy add function from the command line?

In [5]:
# using the help command line
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  **Calling ufuncs:** ``op(*x[, out], where=True, **kwargs)``
 |  
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array object(s) in whic

### 6. Create a null vector of size 10 but the fifth value which is 1

In [7]:
null_vector = np.zeros(10)
print(null_vector)

# Modify the fifth element to be 1
null_vector[4] = 1

print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 7. Create a vector with values ranging from 10 to 49

In [8]:
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 8. Reverse a vector (first element becomes last)

In [10]:
reversed_vector = vector[::-1]
print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
values = np.arange(9)

# using the reshape method
matrix = values.reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [12]:
elements = np.array([1, 2, 0, 0, 4, 0])

print(np.nonzero(elements))

# The output indicates that the non-zero elements are located at indices 0, 1, and 4 in the elements array.

(array([0, 1, 4]),)


### 11. Create a 3x3 identity matrix 

In [13]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 12. Create a 3x3x3 array with random values

In [14]:
random_3d_array = np.random.random((3, 3, 3))
print(random_3d_array)

[[[0.90208252 0.2882561  0.97727406]
  [0.17026819 0.13478638 0.26636844]
  [0.50156616 0.42347032 0.06290975]]

 [[0.36574239 0.46468198 0.67926374]
  [0.39828505 0.71038165 0.11328681]
  [0.20122052 0.54570197 0.87589414]]

 [[0.02107776 0.56894616 0.05842541]
  [0.0993137  0.48686705 0.86091613]
  [0.17098492 0.00305991 0.55544015]]]


### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [16]:
random_10x10_array = np.random.random((10, 10))
print(random_10x10_array)
print("\nMinimum value:", np.min(random_10x10_array))
print("Maximum value:", np.max(random_10x10_array))

[[0.09345477 0.22087784 0.58109555 0.72276115 0.76119843 0.44682432
  0.25132009 0.55283628 0.19694895 0.76670559]
 [0.07831311 0.99756957 0.06060545 0.79644658 0.39099952 0.85124481
  0.54543317 0.92814959 0.2676571  0.8889708 ]
 [0.38087238 0.00249127 0.20352705 0.87535782 0.69783172 0.93982443
  0.76226281 0.09604078 0.53555661 0.67570052]
 [0.78138838 0.81305042 0.82975814 0.70822024 0.94821467 0.1734969
  0.15857206 0.36187988 0.51583158 0.51240456]
 [0.43226553 0.03382979 0.69218721 0.17915825 0.02394909 0.91947532
  0.70487319 0.71240306 0.87640171 0.59941673]
 [0.75929489 0.42017729 0.60869813 0.34379099 0.76649132 0.79881744
  0.21770827 0.50912224 0.18468468 0.31171497]
 [0.41441625 0.28126695 0.86087186 0.5050039  0.24394751 0.4626319
  0.79959034 0.02615107 0.33691277 0.03105864]
 [0.37906404 0.11670395 0.88312336 0.24075612 0.07014377 0.87606216
  0.77310402 0.49419875 0.33077424 0.6223608 ]
 [0.1330206  0.14367662 0.40574129 0.63795655 0.83674685 0.9055006
  0.71774797 0.

### 14. Create a random vector of size 30 and find the mean value 

In [17]:
random_vector = np.random.random(30)
print(random_vector)
print("\nMean of random vector: ", np.mean(random_vector))

[0.71948101 0.26784769 0.74588042 0.72526092 0.80438084 0.09882595
 0.46495418 0.22756014 0.69405069 0.40010417 0.77671072 0.57684869
 0.93894893 0.79600034 0.72166303 0.81135956 0.0281242  0.79917019
 0.86203065 0.06276153 0.28424242 0.16762785 0.20447055 0.07279741
 0.06507217 0.08580103 0.4238625  0.25423103 0.27711262 0.98236463]

Mean of random vector:  0.4779848682554875


### 15. Create a 2d array with 1 on the border and 0 inside

In [22]:
array_5x5 = np.ones((5, 5))
print(array_5x5)
array_5x5[1:-1, 1:-1] = 0
print("\n2D Array with 1 on Border and 0 Inside:")
print(array_5x5)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

2D Array with 1 on Border and 0 Inside:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### 16. How to add a border (filled with 0's) around an existing array?

In [23]:
existing_array = np.ones((3, 3))

# using the pad method
bordered_array = np.pad(existing_array, pad_width=1, mode='constant', constant_values=0)
print("Array with Border of 0's:")
print(bordered_array)


Array with Border of 0's:
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


### 17. What is the result of the following expression? 

In [24]:
print("\nResult of expressions:")
print(0 * np.nan)          # nan
print(np.nan == np.nan)    # False
print(np.inf > np.nan)     # False
print(np.nan - np.nan)     # nan
print(np.nan in set([np.nan]))  # True
print(0.3 == 3 * 0.1)      # False


Result of expressions:
nan
False
False
nan
True
False


### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [25]:
matrix = np.diag(1 + np.arange(4), k=-1)
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [26]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\nCheckerboard Pattern:")
print(checkerboard)


Checkerboard Pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [28]:
array_shape = (6, 7, 8)
index_100th_element = np.unravel_index(99, array_shape)
print(index_100th_element)


(1, 5, 3)
