# 100 Numpy Exercises

###  1. Import the numpy package under the name

In [2]:
import numpy as np

### 2.  Print the numpy version and the configuration

In [2]:
print("NumPy Version:", np.__version__)
print("NumPy Configuration:")
print(np.show_config())

NumPy Version: 1.24.3
NumPy Configuration:
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/predictive_an001/miniconda3/envs/datascience/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/predictive_an001/miniconda3/envs/datascience/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/predictive_an001/miniconda3/envs/datascience/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/predictive_an001/miniconda3/envs/datascience/include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/predictive_an001/miniconda3/envs/datascience/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/predictive_an001/miniconda3/envs/datascience/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthre

### 3.  Create a null vector of size 10

In [3]:
null_vector = np.zeros(10)
print("Null vector of size 10:", null_vector)

Null vector of size 10: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 4.  How to find the memory size of any array

In [4]:
array = np.array([1, 2, 3, 4, 5])
print("Memory size of the array:", array.nbytes, "bytes")

Memory size of the array: 40 bytes


### 5. How to get the documentation of the numpy add function from the command line?

In [5]:
# using the help command line
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  **Calling ufuncs:** ``op(*x[, out], where=True, **kwargs)``
 |  
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array object(s) in whic

### 6. Create a null vector of size 10 but the fifth value which is 1

In [7]:
null_vector = np.zeros(10)
print(null_vector)

# Modify the fifth element to be 1
null_vector[4] = 1

print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 7. Create a vector with values ranging from 10 to 49

In [8]:
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 8. Reverse a vector (first element becomes last)

In [10]:
reversed_vector = vector[::-1]
print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
values = np.arange(9)

# using the reshape method
matrix = values.reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [12]:
elements = np.array([1, 2, 0, 0, 4, 0])

print(np.nonzero(elements))

# The output indicates that the non-zero elements are located at indices 0, 1, and 4 in the elements array.

(array([0, 1, 4]),)


### 11. Create a 3x3 identity matrix 

In [13]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 12. Create a 3x3x3 array with random values

In [14]:
random_3d_array = np.random.random((3, 3, 3))
print(random_3d_array)

[[[0.90208252 0.2882561  0.97727406]
  [0.17026819 0.13478638 0.26636844]
  [0.50156616 0.42347032 0.06290975]]

 [[0.36574239 0.46468198 0.67926374]
  [0.39828505 0.71038165 0.11328681]
  [0.20122052 0.54570197 0.87589414]]

 [[0.02107776 0.56894616 0.05842541]
  [0.0993137  0.48686705 0.86091613]
  [0.17098492 0.00305991 0.55544015]]]


### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [16]:
random_10x10_array = np.random.random((10, 10))
print(random_10x10_array)
print("\nMinimum value:", np.min(random_10x10_array))
print("Maximum value:", np.max(random_10x10_array))

[[0.09345477 0.22087784 0.58109555 0.72276115 0.76119843 0.44682432
  0.25132009 0.55283628 0.19694895 0.76670559]
 [0.07831311 0.99756957 0.06060545 0.79644658 0.39099952 0.85124481
  0.54543317 0.92814959 0.2676571  0.8889708 ]
 [0.38087238 0.00249127 0.20352705 0.87535782 0.69783172 0.93982443
  0.76226281 0.09604078 0.53555661 0.67570052]
 [0.78138838 0.81305042 0.82975814 0.70822024 0.94821467 0.1734969
  0.15857206 0.36187988 0.51583158 0.51240456]
 [0.43226553 0.03382979 0.69218721 0.17915825 0.02394909 0.91947532
  0.70487319 0.71240306 0.87640171 0.59941673]
 [0.75929489 0.42017729 0.60869813 0.34379099 0.76649132 0.79881744
  0.21770827 0.50912224 0.18468468 0.31171497]
 [0.41441625 0.28126695 0.86087186 0.5050039  0.24394751 0.4626319
  0.79959034 0.02615107 0.33691277 0.03105864]
 [0.37906404 0.11670395 0.88312336 0.24075612 0.07014377 0.87606216
  0.77310402 0.49419875 0.33077424 0.6223608 ]
 [0.1330206  0.14367662 0.40574129 0.63795655 0.83674685 0.9055006
  0.71774797 0.

### 14. Create a random vector of size 30 and find the mean value 

In [17]:
random_vector = np.random.random(30)
print(random_vector)
print("\nMean of random vector: ", np.mean(random_vector))

[0.71948101 0.26784769 0.74588042 0.72526092 0.80438084 0.09882595
 0.46495418 0.22756014 0.69405069 0.40010417 0.77671072 0.57684869
 0.93894893 0.79600034 0.72166303 0.81135956 0.0281242  0.79917019
 0.86203065 0.06276153 0.28424242 0.16762785 0.20447055 0.07279741
 0.06507217 0.08580103 0.4238625  0.25423103 0.27711262 0.98236463]

Mean of random vector:  0.4779848682554875


### 15. Create a 2d array with 1 on the border and 0 inside

In [22]:
array_5x5 = np.ones((5, 5))
print(array_5x5)
array_5x5[1:-1, 1:-1] = 0
print("\n2D Array with 1 on Border and 0 Inside:")
print(array_5x5)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

2D Array with 1 on Border and 0 Inside:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### 16. How to add a border (filled with 0's) around an existing array?

In [23]:
existing_array = np.ones((3, 3))

# using the pad method
bordered_array = np.pad(existing_array, pad_width=1, mode='constant', constant_values=0)
print("Array with Border of 0's:")
print(bordered_array)


Array with Border of 0's:
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


### 17. What is the result of the following expression? 

In [24]:
print("\nResult of expressions:")
print(0 * np.nan)          # nan
print(np.nan == np.nan)    # False
print(np.inf > np.nan)     # False
print(np.nan - np.nan)     # nan
print(np.nan in set([np.nan]))  # True
print(0.3 == 3 * 0.1)      # False


Result of expressions:
nan
False
False
nan
True
False


### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [25]:
matrix = np.diag(1 + np.arange(4), k=-1)
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [26]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\nCheckerboard Pattern:")
print(checkerboard)


Checkerboard Pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [28]:
array_shape = (6, 7, 8)
index_100th_element = np.unravel_index(99, array_shape)
print(index_100th_element)


(1, 5, 3)


### 21. Create a checkerboard 8x8 matrix using the tile function

In [29]:
row_pattern = np.array([0, 1] * 4)
checkerboard = np.tile(row_pattern, (8, 1))
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]


### 22. Normalize a 5x5 random matrix (★☆☆)

In [30]:
random_matrix = np.random.random((5, 5))
mean_value = np.mean(random_matrix)
std_dev = np.std(random_matrix)

# Normalize the matrix
normalized_matrix = (random_matrix - mean_value) / std_dev

print(random_matrix)
print("\nThe normalized matrix: ")
print(normalized_matrix)

[[0.17835756 0.50586692 0.48092306 0.01290328 0.48807379]
 [0.03811483 0.81539975 0.55761622 0.48751706 0.19632548]
 [0.48252726 0.76863196 0.25929759 0.14175258 0.6158289 ]
 [0.06557847 0.18707225 0.18370243 0.48912378 0.26143143]
 [0.86676314 0.19638433 0.62043214 0.71123461 0.95217884]]

The normalized matrix: 
[[-0.90846583  0.31010499  0.21729586 -1.52407497  0.24390174]
 [-1.43026986  1.46179018  0.50264967  0.2418303  -0.84161222]
 [ 0.22326465  1.28778029 -0.60731061 -1.04466272  0.71924281]
 [-1.32808531 -0.8760409  -0.88857907  0.24780847 -0.59937117]
 [ 1.65289899 -0.84139324  0.73637016  1.0742208   1.97070696]]


### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [31]:
color_dtype = np.dtype([('R', np.uint8),
                        ('G', np.uint8),
                        ('B', np.uint8),
                        ('A', np.uint8)])
print(color_dtype)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [32]:
matrix1 = np.random.random((5,3))
matrix2 = np.random.random((3,2))

# Multiply the matrices
result_matrix = np.dot(matrix1, matrix2)

print(result_matrix)

[[0.3607899  0.19448432]
 [0.43446883 0.21567182]
 [0.34086961 0.16163494]
 [0.43815349 0.25626136]
 [0.88607807 0.42099819]]


### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [33]:
arr_1D = np.array([1, 5, 3, 7, 9, 2, 6, 8, 4])

# Negate elements between 3 and 8
arr_1D[(arr_1D > 3) & (arr_1D < 8)] *= -1

print(arr_1D)

[ 1 -5  3 -7  9  2 -6  8 -4]


### 26. What is the output of the following script? (★☆☆)


In [35]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

### 28. What are the result of the following expressions? (★☆☆)

In [36]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/tmp/ipykernel_2572/548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
/tmp/ipykernel_2572/548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
/tmp/ipykernel_2572/548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

### 29. How to round away from zero a float array ? (★☆☆)

In [37]:
float_array = np.array([-1.5, -0.5, 0.5, 1.5])
rounded_array = np.round(float_array, decimals=-1)
print(rounded_array)

[-0. -0.  0.  0.]


### 30. How to find common values between two arrays? (★☆☆)

In [40]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

common_values = np.intersect1d(array1, array2)
print(common_values)

[3 4 5]


### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [39]:
import warnings

# Ignore all numpy warnings
warnings.filterwarnings('ignore', category=np.VisibleDeprecationWarning)

### 32. Is the following expressions true? (★☆☆)

In [41]:
# This will result in False. np.sqrt(-1) will produce a RuntimeWarning due to taking the square root of a negative number, and it will return nan. np.emath.sqrt(-1) will return the complex number 1j, representing the square root of -1.
np.sqrt(-1) == np.emath.sqrt(-1)

/tmp/ipykernel_2572/889103864.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [53]:
from datetime import datetime, timedelta

# Get today's date
today = np.datetime64('today')

# Calculate yesterday and tomorrow
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2024-02-11
Today: 2024-02-12
Tomorrow: 2024-02-13


### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [54]:
import numpy as np

# Define the start and end dates for July 2016
start_date = np.datetime64('2016-07-01')
end_date = np.datetime64('2016-08-01')

# Generate all the dates for July 2016
july_dates = np.arange(start_date, end_date, dtype='datetime64[D]')

print("Dates in July 2016:")
for date in july_dates:
    print(date)

Dates in July 2016:
2016-07-01
2016-07-02
2016-07-03
2016-07-04
2016-07-05
2016-07-06
2016-07-07
2016-07-08
2016-07-09
2016-07-10
2016-07-11
2016-07-12
2016-07-13
2016-07-14
2016-07-15
2016-07-16
2016-07-17
2016-07-18
2016-07-19
2016-07-20
2016-07-21
2016-07-22
2016-07-23
2016-07-24
2016-07-25
2016-07-26
2016-07-27
2016-07-28
2016-07-29
2016-07-30
2016-07-31


### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [51]:
A = np.random.random((5, 5))
B = np.random.random((5, 5))

np.add(A, B, out=A)
np.negative(A, out=A)
np.divide(A, 2, out=A)
np.multiply(A, B, out=A)

print("Result:", A)

Result: [[-0.35419635 -0.91942165 -0.07019667 -0.38398421 -0.15529713]
 [-0.43778619 -0.22313186 -0.2910285  -0.010164   -0.31000721]
 [-0.26037351 -0.00877425 -0.0647907  -0.16990598 -0.08117934]
 [-0.71372617 -0.51835062 -0.02754074 -0.26797715 -0.1596201 ]
 [-0.67002829 -0.35168367 -0.36913702 -0.28741146 -0.72880031]]


### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [50]:
random_array = np.random.random((5, 5)) * 10  # Generating random positive numbers
integer_part_method1 = random_array.astype(int)
integer_part_method2 = np.trunc(random_array)
integer_part_method3 = np.floor(random_array)
integer_part_method4 = np.ceil(random_array) - 1

print("Method 1 (astype):", integer_part_method1)
print("Method 2 (trunc):", integer_part_method2)
print("Method 3 (floor):", integer_part_method3)
print("Method 4 (ceil):", integer_part_method4)

Method 1 (astype): [[5 2 8 7 6]
 [4 5 2 1 2]
 [1 8 5 6 3]
 [5 3 6 7 7]
 [3 0 6 9 3]]
Method 2 (trunc): [[5. 2. 8. 7. 6.]
 [4. 5. 2. 1. 2.]
 [1. 8. 5. 6. 3.]
 [5. 3. 6. 7. 7.]
 [3. 0. 6. 9. 3.]]
Method 3 (floor): [[5. 2. 8. 7. 6.]
 [4. 5. 2. 1. 2.]
 [1. 8. 5. 6. 3.]
 [5. 3. 6. 7. 7.]
 [3. 0. 6. 9. 3.]]
Method 4 (ceil): [[5. 2. 8. 7. 6.]
 [4. 5. 2. 1. 2.]
 [1. 8. 5. 6. 3.]
 [5. 3. 6. 7. 7.]
 [3. 0. 6. 9. 3.]]


### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [48]:
matrix = np.zeros((5, 5))
matrix += np.arange(5)
print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [47]:
def generator_function():
    for i in range(10):
        yield i

array = np.fromiter(generator_function(), dtype=int)
print(array)

[0 1 2 3 4 5 6 7 8 9]


### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [46]:
vector = np.linspace(0, 1, 12)[1:-1]
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


### 40. Create a random vector of size 10 and sort it (★★☆)

In [45]:
random_vector = np.random.random(10)
sorted_vector = np.sort(random_vector)
print(sorted_vector)

[0.08141669 0.1628497  0.21779258 0.23508328 0.24111264 0.25059294
 0.32213795 0.43780131 0.44969431 0.9397223 ]


### 41. How to sum a small array faster than np.sum? (★★☆)

### 42. Consider two random array A and B, check if they are equal (★★☆)

In [44]:
A = np.random.random((5, 5))
B = np.random.random((5, 5))

are_equal = np.array_equal(A, B)
print("Are A and B equal?", are_equal)

Are A and B equal? False


### 43. Make an array immutable (read-only) (★★☆)

In [43]:
array = np.zeros(10)
array.flags.writeable = False

### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [42]:
cartesian_coordinates = np.random.random((10, 2))
x, y = cartesian_coordinates[:, 0], cartesian_coordinates[:, 1]
r = np.linalg.norm(cartesian_coordinates, axis=1)
theta = np.arctan2(y, x)

polar_coordinates = np.column_stack((r, theta))
print("Polar Coordinates:", polar_coordinates)

Polar Coordinates: [[0.55433022 1.4769635 ]
 [0.76195549 0.98951571]
 [0.48079163 1.11363463]
 [0.63632574 0.36595378]
 [0.94375262 0.27466835]
 [0.707707   0.94336611]
 [0.38318069 0.49081616]
 [0.73243687 0.75470722]
 [0.75978078 0.02308093]
 [0.82452211 0.20322421]]


### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [55]:
random_vector = np.random.random(10)

max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

print(random_vector)

[0.         0.26514674 0.38783636 0.51520234 0.41091222 0.40120733
 0.74593409 0.59954823 0.22315985 0.3057498 ]


### 46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area (★★☆)

In [56]:
# Create structured array with x and y coordinates
x = np.linspace(0, 1, 5)
y = np.linspace(0, 1, 5)
X, Y = np.meshgrid(x, y)
structured_array = np.zeros((5, 5), dtype=[('x', float), ('y', float)])
structured_array['x'] = X
structured_array['y'] = Y

print(structured_array)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [57]:
# Example arrays X and Y
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

# Construct Cauchy matrix
C = 1 / (X[:, None] - Y)

print("Cauchy matrix:")
print(C)


Cauchy matrix:
[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

### 49. How to print all the values of an array? (★★☆)

In [59]:
# Create an array
arr = np.arange(100)

# Set print options to print all values
np.set_printoptions(threshold=np.inf)

# Print the array
print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [60]:
vector = np.array([1, 2, 3, 4, 5])

# Given scalar
scalar = 2.5

# Find the index of the closest value to the scalar
closest_index = np.abs(vector - scalar).argmin()

# Closest value
closest_value = vector[closest_index]

print("Closest value to", scalar, "is", closest_value)

Closest value to 2.5 is 2


### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [3]:
dtype_pos = [('x', float), ('y', float)]
dtype_color = [('r', int), ('g', int), ('b', int)]

# Create structured array
positions = np.array([(1.0, 2.0), (3.0, 4.0)], dtype=dtype_pos)
colors = np.array([(255, 0, 0), (0, 255, 0)], dtype=dtype_color)

# Combine position and color arrays
structured_array = np.empty(2, dtype=[('position', dtype_pos), ('color', dtype_color)])
structured_array['position'] = positions
structured_array['color'] = colors

print(structured_array)

[((1., 2.), (255,   0, 0)) ((3., 4.), (  0, 255, 0))]


### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [4]:
# Generate random vector with shape (100,2)
vector = np.random.rand(100, 2)

# Calculate point by point distances
distances = np.sqrt(np.sum((vector - vector[:, np.newaxis])**2, axis=-1))

print(distances)

[[0.         0.54528944 0.39878734 ... 0.30384387 0.30748942 0.07683385]
 [0.54528944 0.         0.26049073 ... 0.30676453 0.47840183 0.4856562 ]
 [0.39878734 0.26049073 0.         ... 0.09494956 0.4933461  0.37051772]
 ...
 [0.30384387 0.30676453 0.09494956 ... 0.         0.42388996 0.27800201]
 [0.30748942 0.47840183 0.4933461  ... 0.42388996 0.         0.23965853]
 [0.07683385 0.4856562  0.37051772 ... 0.27800201 0.23965853 0.        ]]


### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [5]:
float_array = np.array([1.5, 2.7, 3.9], dtype=np.float32)

# Convert to integer in place
float_array.view(dtype=np.int32)[:] = float_array

print(float_array)

[1.e-45 3.e-45 4.e-45]


### 54. How to read the following file? (★★☆)

In [13]:
# Read the file, specifying the delimiter and handling missing values
data = np.genfromtxt('file.txt', delimiter=',', filling_values=np.nan)

print(data)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [12]:
arr = np.array([[1, 2], [3, 4]])

# Enumerate over the numpy array
for index, value in np.ndenumerate(arr):
    print(index, value)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [11]:
def gaussian_2d(shape, sigma):
    m, n = [(s-1.)/2. for s in shape]
    y, x = np.ogrid[-m:m+1,-n:n+1]
    h = np.exp(-(x*x + y*y) / (2.*sigma*sigma))
    h[h < np.finfo(h.dtype).eps*h.max()] = 0
    return h

# Generate Gaussian-like array
gaussian_array = gaussian_2d((5, 5), sigma=1.0)

print(gaussian_array)

[[0.01831564 0.082085   0.13533528 0.082085   0.01831564]
 [0.082085   0.36787944 0.60653066 0.36787944 0.082085  ]
 [0.13533528 0.60653066 1.         0.60653066 0.13533528]
 [0.082085   0.36787944 0.60653066 0.36787944 0.082085  ]
 [0.01831564 0.082085   0.13533528 0.082085   0.01831564]]


### 57. How to randomly place p elements in a 2D array? (★★☆)

In [10]:
def random_placement_2d_array(shape, p):
    arr = np.zeros(shape)
    indices = np.random.choice(np.prod(shape), p, replace=False)
    arr.flat[indices] = 1
    return arr

# Generate 2D array with randomly placed elements
result = random_placement_2d_array((5, 5), 3)

print(result)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0.]]


### 58. Subtract the mean of each row of a matrix (★★☆)

In [9]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Subtract the mean of each row
result = matrix - matrix.mean(axis=1, keepdims=True)

print(result)

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


### 59. How to sort an array by the nth column? (★★☆)

In [8]:
array = np.array([[1, 4], [3, 2], [2, 3]])

# Sort array by the second column
sorted_array = array[array[:, 1].argsort()]

print(sorted_array)

[[3 2]
 [2 3]
 [1 4]]


### 60. How to tell if a given 2D array has null columns? (★★☆)

In [7]:
array = np.array([[1, 0, 3], [0, 0, 0], [4, 0, 6]])

# Check if any column has all zeros
has_null_columns = np.all(array == 0, axis=0).any()

print(has_null_columns)

True


### 61. Find the nearest value from a given value in an array (★★☆)

In [14]:
array = np.array([1, 3, 5, 7, 9])

# Given value
value = 6

# Find the nearest value
nearest_value = array[np.abs(array - value).argmin()]

print(nearest_value)

5


### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [15]:
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4], [5], [6]])

# Initialize iterator
iterator = np.nditer([arr1, arr2])

# Compute sum using iterator
sum_result = 0
for x, y in iterator:
    sum_result += x + y

print(sum_result)

63


### 63. Create an array class that has a name attribute (★★☆)

In [16]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name=''):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None:
            return
        self.name = getattr(obj, 'name', '')

# Create an array with a name attribute
arr = NamedArray([1, 2, 3], name='Example Array')

print(arr)
print(arr.name)

[1 2 3]
Example Array


### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [17]:
vector = np.array([1, 2, 3, 4, 5])

# Given index vector
index_vector = np.array([0, 1, 1, 2, 3, 3])

# Add 1 to elements indexed by index vector, handling repeated indices
np.add.at(vector, index_vector, 1)

print(vector)

[2 4 4 6 5]


### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [18]:
X = np.array([1, 2, 3, 4, 5])

# Given index list I
I = np.array([1, 3, 4, 2, 3])

# Initialize array F with zeros
F = np.zeros_like(X)

# Accumulate elements of X to F based on index list I
np.add.at(F, I, X)

print(F)

[0 1 4 7 3]


### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? (★★★)

### 69. How to get the diagonal of a dot product? (★★★)

### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

### 72. How to swap two rows of an array? (★★★)

### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles (★★★)

### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

### 75. How to compute averages using a sliding window over an array? (★★★)

### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary) (★★★)

### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

### 82. Compute a matrix rank (★★★)

### 83. How to find the most frequent value in an array?

### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

### 88. How to implement the Game of Life using numpy arrays? (★★★)

### 89. How to get the n largest values of an array (★★★)

### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

### 91. How to create a record array from a regular array? (★★★)

### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

### 95. Convert a vector of ints into a matrix binary representation (★★★)

### 96. Given a two dimensional array, how to extract unique rows? (★★★)

### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)